### ISSUE TITLE
API is inconsistent

### ISSUE THREAD

**Issue by dispatchrabbi** [gillstrom/osx-brightness#2]
When calling `get`, the brightness is returned as a float (e.g., `0.75`). When calling `set`, the brightness is given as an int (e.g. `75`).

The module should have a consistent API (floats or ints), or the reason for the inconsistency should be documented.

**Comment by sindresorhus** [comment]
:+1: Should use floats for both.

**Comment by kevva** [comment]
Even for the CLI?

**Comment by gillstrom** [comment]
Changed api to use floats :+1:
