### ISSUE TITLE
throw vs cb if value 

### ISSUE THREAD

**Issue by stevemao** [gillstrom/osx-brightness#4]
If I type `brightness 2` the whole stack is blowing in my console

```
Error: Expected a value between 0 and 1
    at Object.exports.set (/usr/local/lib/node_modules/brightness/node_modules/osx-brightness/index.js:73:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/brightness/cli.js:27:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Any reason this is throwing an error not `cb` with an error?

``` js
    if (typeof val !== 'number' || isNaN(val) === 'true' || val < 0 || val > 1) {
        throw new Error('Expected a value between 0 and 1');
    }
```

**Comment by kevva** [comment]
It's sort of a type annotation thing. But yeah, maybe we could fallback gracefully setting it to `1` if `>1`.

**Comment by stevemao** [comment]
I would like to see the error (at least a warning if you wanna fallback). If you have a good reason to `throw` maybe just `catch` it?

**Comment by kevva** [comment]
Yeah, in the CLI that makes sense.

**Comment by stevemao** [comment]
@kevva Just out of curiosity, do you know any link that tells you how to handle errors? This is a perfect example I think I would `cb` the error. Or can you elaborate why you should definitely throw the error here.

**Comment by stevemao** [comment]
``` js
if (typeof val !== 'number' || isNaN(val) === 'true' || val < 0 || val > 1)
```

Is probably checking too much at the same time. If it's a type error it's definitely `throw`

**Comment by kevva** [comment]
99% of the times, `cb` is correct. But for input errors throwing can be good. This is sort of a type error but not exactly so I guess it could be changed.

**Comment by stevemao** [comment]
:+1: exactly what I think
