### ISSUE TITLE
Support multi screen?

### ISSUE THREAD

**Issue by stevemao** [gillstrom/osx-brightness#5]

**Comment by gillstrom** [comment]
Sorry for the extremely late answer. 

I don't have any monitors to test with, is it possible to control a monitors brightness from the computer though?

**Comment by stevemao** [comment]
I don't have an external monitor now. But from the last test no.

**Comment by kevva** [comment]
This is not possible, no.

**Comment by stevemao** [comment]
Why is it not possible?

**Comment by kevva** [comment]
You can't control brightness on external monitors as far as I know. Might be different with a Thunderbolt display though.

**Comment by Hultner** [comment]
You can control the LG Ultrafine displays via System Preferences and the touchbar but haven't been able to using this tool
